name: CI

on:
  push:

env:
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}   
  AWS_SMARTBINMS_IP: ${{ vars.AWS_SMARTBINMS_IP }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17' 
        distribution: 'temurin'

    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Set execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload JUnit Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: junit-test-reports
        path: build/reports/tests/test/index.html
  

        
