name: CI

on:
  push:

env:
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}   
  AWS_SMARTBINMS_IP: ${{ vars.AWS_SMARTBINMS_IP }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Set execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SmartBinMSBootjar
        path: build/libs/SmartBinMS-0.0.1-SNAPSHOT.jar
  

        
