name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GRADLE_USER_HOME
      run: |
        GRADLE_USER_HOME="$(pwd)/.gradle"
        export GRADLE_USER_HOME
      shell: bash


    - name: Set execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew --build-cache assemble


    - name: Archive Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: build/libs/SmartBinMS-0.0.1-SNAPSHOT.jar
