name: CI

on:
  push:

env:
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}   
  AWS_SMARTBINMS_IP: ${{ vars.AWS_SMARTBINMS_IP }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GRADLE_USER_HOME
      run: |
        GRADLE_USER_HOME="$(pwd)/.gradle"
        export GRADLE_USER_HOME
      shell: bash

    - name: Set execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew --build-cache assemble

    - name: Archive Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: build/libs/SmartBinMS-0.0.1-SNAPSHOT.jar



  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set permissions for private key
      run: |
        echo "$AWS_PRIVATE_KEY" > key.pem
        chmod 400 key.pem

    - name: Stop all running container and remove service volume
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$AWS_SMARTBINMS_IP 'sudo docker-compose stop || true'

    - name: Copy new boot jar
      run: |
        scp -o StrictHostKeyChecking=no -i key.pem  ~/build/libs/SmartBinMS-0.0.1-SNAPSHOT.jar ubuntu@$AWS_SMARTBINMS_IP:/home/ubuntu

    - name: Up the system with all containers
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$AWS_SMARTBINMS_IP 'cd ~ ; sudo docker-compose up -d'
