name: CI

on:
  push:

env:
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}   
  AWS_SMARTBIN_IP: ${{ secrets.AWS_SMARTBIN_IP}}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GRADLE_USER_HOME
      run: |
        GRADLE_USER_HOME="$(pwd)/.gradle"
        export GRADLE_USER_HOME
      shell: bash

    - name: Set execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Restore Gradle Cache
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: cache-${{ github.ref }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: cache-${{ github.ref }}

    - name: Build with Gradle
      run: ./gradlew build assemble

    - name: Save Gradle Cache
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: cache-${{ github.ref }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}


    - name: Archive Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: build/libs/SmartBinMS-0.0.1-SNAPSHOT.jar
